DIV-5419: DN landing page: deemed dispensed not approved
hmcts/div-petitioner-frontend pull request #750
Opened 2020-08-24 14:47 UTC by madjava

# Description

https://tools.hmcts.net/jira/browse/DIV-5419

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-08-24 14:52 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> +
Fetching enforcement and application without fee from fees and payment service

2020-08-24 14:53 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> +};
Adding middleware functionality to go get the fee from the service

2020-08-24 14:54 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.test.js
> +  });
Adding test cases to cover the two extra fees fetched from fees and pay service

2020-08-24 14:55 UTC, madjava commented on app/services/mocks/feesAndPaymentsService.js
> +    };
Setting up the system for two additional fee detail

2020-08-24 14:56 UTC, madjava commented on app/steps/amendment-explanatory-page/content.json
> +          }
Adding list of d8 documents for display. This is how its done on DN also, imitating the same on PFE to facilitate listing of divorce documents

2020-08-24 14:56 UTC, madjava commented on app/steps/amendment-explanatory-page/content.json
> +        }
Reasons as discribed above

2020-08-24 14:57 UTC, madjava commented on app/steps/amendment-explanatory-page/template.html
> +{% from "common/components/customPageComponents.html" import documentList, nextStep %}
Renaming as file is now used by new screen also, giving it a more relevant name for its use now

2020-08-24 14:59 UTC, madjava commented on app/steps/amendment-explanatory-page/template.html
> + {% include "includes/sideMenu.html" %}
Side menu content extracted and added to a `sidemenu.html` file. This is how its done on DN also and make it so easy to reuse whenever a screen needs to display documents. No need to duplicate in other place. We can simply include this one file

2020-08-24 15:01 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +};
Functionality for the new screen.

2020-08-24 15:04 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +});
Test case for new functionality

2020-08-24 15:04 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% endblock %}
Template for new screen. Reusing the `sidemenu.html` here also

2020-08-24 15:06 UTC, madjava commented on app/views/common/components/customPageComponents.html
>                </a>
Refactoring the download documents feature to display documents correctly

2020-08-24 15:06 UTC, madjava commented on app/views/includes/sideMenu.html
> +</aside>
Reusable side menu layout for use in PFE

2020-08-24 15:09 UTC, madjava commented on config/default.yaml
> +    amount: 50.00
Adding the required fee code for display in SA not approved screen

2020-08-24 15:10 UTC, madjava commented on config/default.yaml
> +    - 'ServiceApplicationNotApproved'
Adding new case state to list so PFE does not redirect to DN

2020-08-24 15:10 UTC, madjava commented on config/default.yaml
> +    - 'DeemedServiceRefused'
Whitelisting service refusal documents

2020-08-24 15:10 UTC, madjava commented on test/end-to-end/helpers/SessionHelper.js
> +  serviceApplicationNotApprovedSession
Adding mock session data for end-2-end test

2020-08-24 15:11 UTC, madjava commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +});
Checking that when case is in right state PFE redirects to the correct endpoint

2020-08-24 18:17 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> -  </p>
Reverting attempt to solve A11y breaking build. Solution above

2020-08-24 18:20 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +
Fix to solve A11y issues. A11y configuration was complaining about the a tag link to the download document and wants me to put it as a parent element which is not what we want here, had a look through the code base and found some places where this fix solved similar issues and implementing the same. Basically what's happening here is me say to the A11y setup to "trust me" i know what am doing  😉

2020-08-24 19:26 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> +        CONF.commonProps.appWithoutNoticeFee = JSON.parse(response);
The evils of copy paste 😜 , now using proper variable name.

2020-08-24 19:28 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +            "linkSummary": "I believe my {{ divorceWho }} lives at that address, but chose not to respond (£{{ feeToEnforce }})",
Name was clashing with a value of same name in the global CONF property and the template engine give that precedence than the once defined in my class, had to use a different name as `[object object]` was the output in the HTML.

2020-08-25 08:51 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> -  }
Using lodash instead of custom function

2020-08-25 08:59 UTC, Dizrupto commented on app/middleware/submissionMiddleware.js
> +const SERVICE_APPLICATION_NOT_APPROVED_PATH = '/service-application-not-approved';
Just checking, why did we decide to do it on PFE in the end?

2020-08-25 09:20 UTC, madjava commented on app/middleware/submissionMiddleware.js
> +const SERVICE_APPLICATION_NOT_APPROVED_PATH = '/service-application-not-approved';
Started out on DN, problem is with DN the landing page is the progress bar, the depending on the sub templates defined the user can either navigate to another page or have a default view. The case number and name would always show could not find a way to land on this page directly on DN, PFE on the other hand has that facility

2020-08-25 09:24 UTC, Dizrupto commented on app/middleware/submissionMiddleware.js
> +const SERVICE_APPLICATION_NOT_APPROVED_PATH = '/service-application-not-approved';
Oh okay I see, I guess as long as Jeremy is okay with it that's fine.

2020-08-25 09:24 UTC, Dizrupto approved these changes

2020-08-25 11:46 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +};
Reverted this now using Lodash instead

2020-08-25 12:32 UTC, jvictorcf reviewed
A few comments and questions, @madjava

2020-08-25 12:32 UTC, jvictorcf commented on app/steps/amendment-explanatory-page/template.html
> + {% include "includes/sideMenu.html" %}
Nice!

2020-08-25 12:32 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +{% from "phase-banner/macro.njk" import govukPhaseBanner %}
Can you point me to the conditional text mentioned in your story?

2020-08-25 12:32 UTC, jvictorcf commented on app/views/common/components/customPageComponents.html
>                </a>
How is this going to show the "as" part of the old text?

2020-08-25 12:32 UTC, jvictorcf commented on config/default.yaml
> +    amount: 50.00
IMHO, this is a bit misleading.
This has made devs in the past think the fees were hardcoded.

If we can live without these, I'd remove them.

2020-08-25 12:32 UTC, jvictorcf commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +const saContent = require('app/steps/service-application-not-approved/content.json').resources.en.translation.content;
Can you name this variable more specifically?

2020-08-25 12:32 UTC, jvictorcf commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +
Should we also see one of the documents?

2020-08-25 12:36 UTC, madjava commented on config/default.yaml
> +    amount: 50.00
Thought so myself when i first had a look, but its backed in and i would not want to change it. Its clear though if one follow the code implementation. I'd argue we leave as is

2020-08-25 12:55 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
Yes we could but better here, main reason, at least for this in this case is when testing, more stable and am confident that i am getting the right values

2020-08-25 12:58 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +  getFeeToResendApplication() {
Added them here due to the fact that, as this screen is mainly informational, the `interceptor` method where the data/info is being added to the context really began to look messy. If i had left it that way am pretty sure in reviews i would be told to break it up and make it more legible 😉

2020-08-25 13:07 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> +const updateEnforcementFeeMiddleware = (req, res, next) => {
Very similar yes but they are used as middleware, IIMHO we leave them separate, each one doing only one thing.

2020-08-25 13:21 UTC, madjava commented on app/views/common/components/customPageComponents.html
>                </a>
Could you elaborate further on "as" part, don't seem to get it. Thanks

2020-08-25 13:29 UTC, madjava commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +
I'll take some credit here @jvictorcf for even going this far to write some end-2-end test. I've not used CodeceptJS before but saw the need to cover this scenario in this way. I'll have a look though but... if don't pull it off this time (or taking too much time), at least i've covered some. Would you be able to "accept" it this way at the moment? We can always pass these issues to PET as soon they would be more active on/with PFE i believe

2020-08-25 14:01 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +};
Have you pushed this change already?

2020-08-25 14:04 UTC, jvictorcf commented on app/views/common/components/customPageComponents.html
>                </a>
Sorry, I've commented in the wrong line (which didn't really help).
I'm talking about line 13, actually. You can see that the old text had "download the file xyz as PDF", but it seems to me that your version will output "download the flie xyz PDF"

2020-08-25 14:04 UTC, jvictorcf commented on config/default.yaml
> +    amount: 50.00
Fair enough. Would you mind raising a ticket for them, then?

2020-08-25 14:04 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +
Fair enough

2020-08-25 14:06 UTC, jvictorcf commented on app/middleware/updateApplicationFeeMiddleware.js
> +const updateEnforcementFeeMiddleware = (req, res, next) => {
I agree with leaving them as separate methods. What I meant is that you can re-use the logic between these 3 methods (something like a private method).

2020-08-25 14:07 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +  getFeeToResendApplication() {
You're probably right. IMHO it would look better, but feel free to do as you prefer.

2020-08-25 14:09 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
But if your test scenario is already covering this, that means you can now refactor it confidently.
Otherwise, can you imagine if every new dev adds a new pair of lines for every new doc type.

2020-08-25 14:11 UTC, jvictorcf commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +
Fair enough. If time is pressing us, you can always implement this in a separate PR (while the main functionality is tested).

2020-08-25 14:12 UTC, jvictorcf reviewed
Let me know when all is addressed/answered and I'll have another look, @madjava.

2020-08-25 14:19 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    const documents = this.getDownloadableFiles(session);
Yes, but i don't like that style especially with NodeJS. I would leave this this way

2020-08-25 14:59 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% from "phase-banner/macro.njk" import govukPhaseBanner %}
You can find it in the content file, the `serviceRefusalInfo` property, in the template its the first paragraph.

2020-08-25 14:59 UTC, madjava commented on app/views/common/components/customPageComponents.html
>                </a>
Oh i see. Yes the update is the way it should be, that's how DN renders also. The above test "as PDF" was me in the early days of working on this project.

2020-08-25 14:59 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +  DispenseWithServiceRefused: 'Dispensed service refusal'
I guess so, i believe when Welsh is being added by the PET team some update's would have to be made to the code base in general to accommodate the language. Let me write a note here maybe comment in the Jira ticket also.

2020-08-25 14:59 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      const serviceApplicationType = toLower(session.serviceApplicationType);
Not sure i've see that. Here i am concerned about the service refusal documents only. Not sure if this needs to be "re-used" at the moment. But hopfully in future Jiras if need arises that would be more appropriate

2020-08-25 14:59 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +};
No pushed anything update's yet, looking though, taking note, to see the one i'd make changes now. as i would limit the update for now, defo would not do all 🙃

2020-08-25 14:59 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +  describe('Document rendering', () => {
Humm.... good point, at the moment but if a file does not exist nothing shows on screen, i guess maybe log the fact so when debugging, would have a look.

2020-08-25 14:59 UTC, madjava commented on config/default.yaml
> +    amount: 50.00
I am going to create a list of "issues and enhancements" we feel can be made, create a ticket and let Matt know about it, asking him if he can hand that over to PET. As you are aware our knowledge on PFE is not like e.g. for COS, somethings as you may have notice could be enhanced but treading cautiously anytime i have to work on this project

2020-08-25 15:14 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> +const updateEnforcementFeeMiddleware = (req, res, next) => {
I'll have a look when making updates with a view to but no promises :)

2020-08-25 15:15 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +module.exports = class SaNotApproved extends Step {
Done should be updated in next push

2020-08-25 15:50 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
Type would not be null but an empty string. Using an empty string so that then the Nunjucks engine is doing its processing i don't have to worry about null's

2020-08-25 15:51 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +  describe('Document rendering', () => {
Would be logging to console this fact i.e when no files exists and return empty string values

2020-08-25 15:55 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.test.js
> +          ioRedisClient.set.calledWith(
Not sure about that, current implementation works fine so i would leave this as is for now. Can be extensively addressed another time if opportunity presents itself.

2020-08-25 16:02 UTC, madjava commented on test/end-to-end/paths/serviceApplicationNotApproved.js
> +const saContent = require('app/steps/service-application-not-approved/content.json').resources.en.translation.content;
Updated

2020-08-25 16:18 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% from "phase-banner/macro.njk" import govukPhaseBanner %}
You can find this in the `serviceRefusalInfo` property in the content file and displayed in the second paragraph

2020-08-25 16:20 UTC, madjava commented on app/services/mocks/feesAndPaymentsService.js
>  const feeTypes = {
OK, actually better that way.

2020-08-25 16:39 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +};
Sorry not yet, addressing some issues would make one commit with all the reviews

2020-08-25 17:24 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    const documents = this.getDownloadableFiles(session);
Refactored

2020-08-25 17:26 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +  describe('Document rendering', () => {
Ok

2020-08-25 17:32 UTC, madjava reviewed
@jvictorcf, Regarding your reviews, done my best to address them, obviously not all, any issue you raised that was not addressed would get logged and passed on to PET. The main functionality is in and it's all working as expected. Hopefully future Jira's would pave way for more improvements on PFE just as this has done from the last time we where in this space.

2020-08-25 17:34 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> -
Moving to general location for reuse

2020-08-25 17:36 UTC, madjava commented on app/middleware/updateApplicationFeeMiddleware.js
> -  redisClient.get('commonProps.applicationFee')
Common functionality colocated and reused in all methods in this middleware below

2020-08-25 17:37 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +        expect(uri).to.eql('');
A bit more "Belts and brace" in the test

2020-08-26 09:21 UTC, Dizrupto approved these changes

2020-08-26 09:26 UTC, jacmurphy approved these changes

2020-08-26 09:38 UTC, jvictorcf commented on app/views/common/components/customPageComponents.html
>                </a>
Fair enough.

2020-08-26 09:41 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +module.exports = class SaNotApproved extends Step {
Hasn't been resolved yet.

2020-08-26 09:41 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
This wasn't addressed

2020-08-26 09:46 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +  DispenseWithServiceRefused: 'Dispensed service refusal'
I don't understand why these files need special logic? What's stopping us from just showing them as they appear on the downloadable files list?

2020-08-26 09:47 UTC, jvictorcf commented on app/steps/amendment-explanatory-page/index.test.js
> +        'files.respondentAnswers',
This hasn't been resolved or responded to.

2020-08-26 09:52 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +module.exports = class SaNotApproved extends Step {
Its been updated already, file is now called `ServiceApplicationNotApproved`

2020-08-26 09:54 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +module.exports = class SaNotApproved extends Step {
Sorry, @madjava. I was looking at a different commit.
This is solved.

2020-08-26 09:55 UTC, madjava commented on app/steps/amendment-explanatory-page/index.test.js
> +        'files.respondentAnswers',
This issue, we would have to log it and pass it on to PET, no need to revert the change, best it stays as is and gives room for improvement. It does not block or hamper anything as it stands. We could have a separate conversation on this

2020-08-26 09:56 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +  DispenseWithServiceRefused: 'Dispensed service refusal'
Well i guess its because PFE caters for both English and Welsh.

2020-08-26 09:57 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
I have addressed this and checked in

2020-08-26 09:58 UTC, jvictorcf reviewed
Nice, Felix.
I've written 3 comments in issues that weren't resolved or responded to.

2020-08-26 10:15 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
But you're still not getting it from the downloadableFiles list (like the other documents)

2020-08-26 10:17 UTC, jvictorcf commented on app/steps/amendment-explanatory-page/index.test.js
> +        'files.respondentAnswers',
I'm not saying we should revert the change. I'm just saying that it would be useful to have a comment explaining which of the files will be appearing on the rendered page.

2020-08-26 10:19 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +  DispenseWithServiceRefused: 'Dispensed service refusal'
I'm going to close this one off because it refers to the same question I'm asking on https://github.com/hmcts/div-petitioner-frontend/pull/750#discussion_r477192485

2020-08-26 10:20 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = refusalFiles[type];
Happy to have a conversation about this.

2020-08-26 12:48 UTC, Dizrupto approved these changes

2020-08-26 13:26 UTC, jacmurphy approved these changes

2020-08-26 13:29 UTC, jvictorcf requested changes
@madjava, as per our conversation, I understand the following line breaks the MVC pattern in this app and un-does the bi-lingual nature of this app and therefore this shouldn't be merged.

2020-08-26 14:44 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> -
Ditching the use on the constant variable. Resolving file label from already existing list on content definition where English and Welsh version are catered for

2020-08-26 14:44 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocumentUrl = uri;
Minor refactoring to make values available to template when rendering

2020-08-26 14:45 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +  </p>
Updating layout and using already defined file data to display file label.

2020-08-26 15:28 UTC, jvictorcf requested changes

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
can we please look for an exact match here (since we know exactly what we're looking for)?

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    return session.serviceApplicationType === 'deemed' ? '\'deemed service\'' : '\'dispensed with service\'';
Can you please resolve this in the content file (as per our earlier conversation)? This is "view" and it shouldn't be here (in the "controller").

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocument = type;
This is an improvement, defo. But it's still breaking the bilingual nature of this app.
The same technique used for https://github.com/hmcts/div-petitioner-frontend/pull/750/files#diff-f872299db5dc33c49ef391e4a13a973bR68 will solve this issue as well.

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/service-application-not-approved/content.json
> +          "serviceRefusalInfo": "[CY] The court has refused your application for {{ serviceApplicationTypeLabel }} that your {{ divorceWho }} received the divorce application. You can read the court’
It seems you've only updated the Welsh version.

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +  </p>
Good idea. I didn't see that.
However, you're still going to need to add the content to a file (i.e. it can't be hardcoded in the template).

2020-08-26 15:28 UTC, jvictorcf commented on app/steps/amendment-explanatory-page/index.test.js
> +        'files.respondentAnswers',
@madjava, have you opted for not adding the comment?

2020-08-26 15:32 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +          "serviceRefusalInfo": "[CY] The court has refused your application for {{ serviceApplicationTypeLabel }} that your {{ divorceWho }} received the divorce application. You can read the court’
Ok, missed this bit, would update it.

2020-08-26 15:34 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocument = type;
This is fine, the type of the document comes from DGS and would match the property name in the content which could be either English or Welsh

2020-08-26 15:34 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    return session.serviceApplicationType === 'deemed' ? '\'deemed service\'' : '\'dispensed with service\'';
Ok, would have a look at this also, implement same so its either English or Welsh

2020-08-26 15:37 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
Exact match would not cut it here, the service application type is e.g deemed and the document name starts with deemed. I think this is ok for this logic.

2020-08-26 15:49 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
Why wouldn't exact match work here?

2020-08-26 18:01 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
Request from COS (casedata): `serviceApplicationType` -> `'deemed'`

`downloadableFiles` array: `[{"uri":"/document-download/DeemedServiceRefused.pdf","type":"DeemedServiceRefused","fileType":"pdf"}]`

i am asking for the document type that matches (via starts with) the service application type.
Same for the other refusal document it starts with `dispensed`

2020-08-27 09:02 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +  </p>
Was not very comfortable with this construct `content.serviceName[session.serviceApplicationType]`, refactored abit

2020-08-27 09:03 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% endif %}
Determining the header title before its used below, values from the content file so English or Welsh would show depending on the current active language

2020-08-27 09:30 UTC, Dizrupto commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
There are also 'deemed' and 'dispensed' approved documents, would that cause an issue?

2020-08-27 09:44 UTC, Dizrupto commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
Oh, I can see only the refused documents are added to the 'filesWhiteList' in default.yaml.
So that should be fine for now. However I guess may cause an issue if we add the deemed/dispensed approved documents to the filesWhiteList?

2020-08-27 09:53 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +          "serviceRefusalInfo": "[CY] The court has refused your application for {{ serviceApplicationTypeLabel }} that your {{ divorceWho }} received the divorce application. You can read the court’
Updated

2020-08-27 09:58 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
You are right @Dizrupto, happy to have a conversation with you

2020-08-27 10:06 UTC, jvictorcf requested changes

2020-08-27 10:06 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +  </p>
@madjava, I'm referring to "The court has refused your application for {{ serviceName }} that
    your {{ session.divorceWho }} received the divorce application.
    You can read the court’s reasons for this in the".
We should not have content in the template. All content should be in the content file.

2020-08-27 10:06 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +{% endif %}
I think the best way to do this is to have two different key/value pairs in the content file. Your template can then choose which one to load based on a variable set by your controller.

2020-08-27 10:06 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +  </p>
btw, the same goes for "Your {{ serviceName }} application has been refused"

2020-08-27 10:06 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +  // getServiceApplicationTypeLabel(session) {
Don't forget to remove this comment

2020-08-27 10:06 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocument = type;
Unless absolutely needed, I'd rather you didn't change the session.
This information is supposed to affect only this page (so it should be in either "page" or "request" scope), but because of the way this framework was build, I think the closer we can get to this is using the "context" object (I might be wrong on that).

2020-08-27 10:11 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +  // getServiceApplicationTypeLabel(session) {
oh! casualties of war, deleted

2020-08-27 10:15 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% endif %}
Yes, am sure if you look at the commit history this was the way i implemented it a first. The leads to more logic in template. This is straight forward no further logic needed. i could have done this `content.serviceApplicationLabel['serviceApplicationType']` But i have opted for this form.

2020-08-27 11:13 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +{% endif %}
Updated

2020-08-27 13:24 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      if (type.startsWith(applicationType)) {
@jvictorcf @Dizrupto Made updates to this as suggested, please have a look, let me have your views. No more starts with, like @Dizrupto noted, possible we could have another document in the future that starts with 'deemed' and to be sown on PFE then previous implementation would falls apart fast.

2020-08-27 13:27 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +  </p>
@jvictorcf. Yes, not good. All content have been move back to the content file.

2020-08-27 13:28 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +          "serviceRefusalInfo": "The court has refused your application for {{ serviceName }} that your {{ divorceWho }} received the divorce application. You can read the court’s reasons for this in
Moving these back here, there they really only should be. Template now renders based on whats in the content file. CY section exists also

2020-08-27 13:30 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +  }
Turns out, after like 1000 breakpoints :) that i actually have a handle on the content.

2020-08-27 13:31 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +        expect(fileUri).to.eql('');
Making names abit more descriptive of purpose

2020-08-27 13:31 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> -
Removing this from the template

2020-08-27 13:33 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> -  </p>
Removing this from the template, its breaks the bilingual nature of the project of the layout

2020-08-27 15:37 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    return document;
Refactoring code logic to fetch correct document type for use in template

2020-08-27 15:56 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocument = type;
Updated

2020-08-27 15:57 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    session.refusalDocument = type;
Updated

2020-08-27 16:08 UTC, jvictorcf reviewed
Only minor comments now, @madjava. Nearly there.

2020-08-27 16:08 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +      .map(file => {
Small comment: you're using the map as a peek (i.e. you're changing the value of the "document" variable instead of using what the map function returns).
Is there a possibility that you will ever return an empty document here? If not, then I think what you want here is something like this:
`let downloadableFiles = [{uri: '1', label: '2'}, {uri: '3', label: '4'}];
return downloadableFiles
  .filter(file => file.uri === '1')
  .map(file => {
    return {fileUri: file.uri, fileLabel: file.label};
  })
  [0]`

This is an example I've run in my console.

2020-08-27 16:08 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +  }
Is the language always present in the session?

2020-08-27 16:08 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = fileLabel;
Minor comment: If you want to call this variable "refusalDocumentLabel", I wouldn't mind.

2020-08-27 16:11 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = fileLabel;
ok, i.e `refusalDocument` -> `refusalDocumentLabel`

2020-08-27 16:13 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +            "deemed": "'deemed service'",
ok

2020-08-27 16:13 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      .filter(file => {
the lint set up for PFE did not allow that, hence had to do is this way

2020-08-27 16:15 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +    ctx.refusalDocument = fileLabel;
ok

2020-08-27 16:28 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      .map(file => {
Ok would try that, if the Linting configured for PFE does not allow i'd revert.

2020-08-27 16:50 UTC, madjava commented on app/steps/service-application-not-approved/index.js
> +      .map(file => {
Done, the Linting is ok with this construct

2020-08-28 08:13 UTC, jvictorcf reviewed
Just a comment/question, @madjava.

2020-08-28 08:13 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.js
> +      })[0];
@madjava. Do you have any unit tests for when the document is not in the list?
is that a possible scenario?
if so, I'd say you can't really just get the [0]. You might have to cater for this scenario.
And if you don't have those tests, you might want to write them.

2020-08-28 08:42 UTC, jvictorcf approved these changes
Nice, @madjava. Looks good to me.

2020-08-28 08:58 UTC, Dizrupto approved these changes

2020-08-28 09:15 UTC, jacmurphy approved these changes

2020-08-28 12:14 UTC, jvictorcf approved these changes
A few minor comments. No show-stoppers.

2020-08-28 12:14 UTC, jvictorcf commented on app/steps/service-application-not-approved/content.json
>              "dispensed": "[CY] dispensed with service"
You might want to match the english version. If you don't, I'm fine with it as well.

2020-08-28 12:14 UTC, jvictorcf commented on app/steps/service-application-not-approved/template.html
> +  <p class="govuk-body">{{ content.serviceRefusalInfo[session.serviceApplicationType] | safe }}</p>
Assuming the session.serviceApplicationType will always be in the session, that's fine.
If not, you can always write a method in your class and call it here.

2020-08-28 12:16 UTC, jacmurphy submitted a review, later dismissed

2020-08-28 12:21 UTC, madjava commented on app/steps/service-application-not-approved/template.html
> +  <p class="govuk-body">{{ content.serviceRefusalInfo[session.serviceApplicationType] | safe }}</p>
Yes, its part of the case data that returns from COS

2020-08-28 12:22 UTC, madjava commented on app/steps/service-application-not-approved/content.json
>              "dispensed": "[CY] dispensed with service"
Yes, updating

2020-08-28 13:30 UTC, Dizrupto approved these changes

2020-08-28 13:31 UTC, jacmurphy approved these changes

2020-09-01 11:36 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +          "refusalDocumentInfo": "You can read the court’s reasons for this in the <a class=\"govuk-link\" aria-label=\"This link will download the file\" href=\"{{ refusalDocumentUri }}\" target=\"_
Extracting duplicated content. Same for the CY section

2020-09-01 11:39 UTC, madjava commented on test/util/assertions.js
> +
Some content have things like single quote and html entitles, adding a new test function to test those type instead of just simply excluding them from the list of items to test

2020-09-01 12:26 UTC, jvictorcf commented on app/steps/service-application-not-approved/content.json
> +          "noResponseOptions": "[CY] If there’s still no response using the original address, you have the following options available to you, depending on your situation.",
Did we already have a Welsh translation for this?
By the way, if this is a new page, how come we have so much Welsh stuff in the context?

2020-09-01 12:26 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.test.js
> +      let deemedDataContent = {};
It seems this could be a constant, couldn't it?

2020-09-01 12:26 UTC, jvictorcf commented on test/util/assertions.js
> +
There's an attribute in the previous test function that allows you to tell it which pieces of content you want to have in the rendered page. Would that not have done it for you?

2020-09-01 12:29 UTC, madjava commented on app/steps/service-application-not-approved/content.json
> +          "noResponseOptions": "[CY] If there’s still no response using the original address, you have the following options available to you, depending on your situation.",
The content for the details part is the same as that for DN No response, to took much if it from there, however there where some variations which i have used the English so as not to second guess what the welsh might be

2020-09-01 12:32 UTC, madjava commented on test/util/assertions.js
> +
I believe you are referring to the exclude property, if that so,  then that tells you which piece of cntent not to test, in our case however i want to test the content 'deemed service' and because of the quite in the text content thats why it could not find an exact match as it compare it with the html entity value and had to use the exclude property

2020-09-01 12:33 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +      let deemedDataContent = {};
i am assigning to in in the before section so not using const in this case

2020-09-01 12:36 UTC, jvictorcf commented on app/steps/service-application-not-approved/index.test.js
> +      let deemedDataContent = {};
yes, but the value you assign to it is always the same, right? So, it could be a constant instead, couldn't it?

2020-09-01 12:37 UTC, jvictorcf commented on app/steps/service-application-not-approved/content.json
> +          "noResponseOptions": "[CY] If there’s still no response using the original address, you have the following options available to you, depending on your situation.",
gotcha

2020-09-01 12:38 UTC, jvictorcf commented on test/util/assertions.js
> +
There are two properties called "includes...". includeValues and includeContent, I believe.

2020-09-01 12:45 UTC, madjava commented on app/steps/service-application-not-approved/index.test.js
> +      let deemedDataContent = {};
Yes, as i am assigning to the variable in this way 
`let dispenseDataContent = {};
      beforeEach(done => {
        dispenseDataContent = Object.assign(...`  
i cant use the const

2020-09-01 12:57 UTC, madjava commented on test/util/assertions.js
> +
@jvictorcf Not see these before, could you point me to where?

2020-09-02 11:28 UTC, jvictorcf approved these changes

2020-09-02 11:28 UTC, jvictorcf commented on test/util/assertions.js
> +exports.testContent = (done, agent, underTest, content, session = {}, excludeKeys = [], dataContent = {}, hasEntities = false) => {
Nice!

2020-09-02 12:39 UTC, jacmurphy approved these changes

2020-09-02 12:39 UTC, yarpo approved these changes

2020-09-02 13:13 UTC, madjava commented
All reviews have been done and PR has been tested and is ready to be merged.

2020-09-02 13:14 UTC, merged