TA-59 Welsh E2E Tests
hmcts/div-petitioner-frontend pull request #771
Opened 2020-11-05 13:16 UTC by phaniperla

# Description

Welsh E2E tests
https://tools.hmcts.net/jira/browse/TA-59

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

local

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-11-05 13:37 UTC, marianadpereira submitted a review, later dismissed

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/check-your-answers/check-your-answers.js
> +    I.checkMyAnswers('cy');
We can just pass it I.checkMyAnswers(language) and move it out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/equality/equality.js
> +      I.seeCurrentUrlEquals(pagePath);
this line is common for both if else so move it out..even the if condition ' if (url.startsWith(pcqAAT)) {' is same so move language check onciditon inside

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/financial/advice.js
> +  if (language === 'en') {
same code no need of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/financial/arrangements.js
> +    I.navByClick(commonContent.continue);
this line can be moved out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-3rd-party-details.js
> +    I.navByClick(commonContent.continue);
same condition no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-details.js
> +    I.navByClick(commonContent.continue);
same logic no need of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-second-hand-info.js
> +    I.fillField('reasonForDivorceAdulterySecondHandInfoDetails', mockSession.reasonForDivorceAdulterySecondHandInfoDetails);
these three line are common, so move out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-when.js
> +    I.navByClick(commonContent.continue);
move this line out of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-where.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/adultery-wish-to-name.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/desertion-agree.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/desertion-date.js
> +    I.navByClick(commonContent.continue);
no need of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/desertion-details.js
> +  if (language === 'en') {
no need of if else condiiton

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/lived-apart-since.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/separation-date-new.js
> +    I.navByClick(commonContent.continue);
no need of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
> +    I.navByClick(commonContent.continue);
no need of if else condiiton

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/help/need-help.js
> +    I.retry(2).click(needHelp ? needHelpContent.yes : needHelpContent.no);
no need of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/help/with-fees.js
> +    if (appliedForFees) {
these lines can be moved out of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/index/index.js
> +      I.navByClick(commonContent.signIn);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/legal/legal-proceedings.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/living-arrangements/live-together.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/certificate-names.js
> +    I.navByClick(commonContent.continue);
no need of if else condiiton

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/date.js
> +    I.navByClick(commonContent.continue);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/husband-or-wife.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/married-in-uk.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/names.js
> +    I.navByClick(commonContent.continue);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/pay/pay-online-only.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/petitioner/changed-name.js
> +    I.retry(2).click(changedNameContent.yes);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/petitioner/confidential.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/petitioner/contact-details.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/petitioner/use-home-address.js
> +    I.scrollPageToBottom();
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/prayer/claim-costs.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/respondent/use-home-address.js
> +    I.navByClick(commonContent.continue);
move this line out of if else condition

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/screening-questions/has-marriage-broken.js
> +    I.retry(2).click(marriageBrokenContent.yes);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/screening-questions/has-marriage-cert.js
> +    I.retry(2).click(marriageCertContent.yes);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/screening-questions/has-respondent-address.js
> +    I.retry(2).click(respondentAddContent.yes);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/screening-questions/language-preference.js
> +    I.retry(2).click(languageContent.yes);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/pages/screening-questions/read-financial-remedy.js
> +    I.navByClick(commonContent.continue);
no need of if else

2020-11-12 07:13 UTC, mounikahmcts commented on test/end-to-end/paths/exitScenarios.js
> +}).retry(1);
is it retry 1 or 3?

2020-11-12 11:16 UTC, Rob-Doherty commented on bin/run-functional-tests.sh
> +export E2E_WAIT_FOR_TIMEOUT_VALUE=${E2E_WAIT_FOR_TIMEOUT_VALUE:-60000}
Doesn't this seem like a pretty big timeout for e2e test steps? I'd understand if it was for nightly crossbrowser, but for headless Puppeteer tests?
It seems like it might slow down the feedback if every step has up to a minute to complete? Some tests like **basicDivorce.js** have retries at the step and scenario level, meaning a failing step could run up to 9 times

2020-11-12 14:55 UTC, Rob-Doherty reviewed
A few points, mainly to do with 
- consistently following your dynamic language declaration that avoids the need for multiple versions of the same steps
- un-skipping scenarios
- a couple questions on some potentially useful test code being removed
- a bit of new code that doesn't look to be used

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/financial/arrangements.js
> +    I.navByClick(commonContent.continue);
yeah this would be better done using your format from line 8 above (but for page-specific content)

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/adultery-when.js
> +    I.navByClick(commonContent.continue);
another candidate for following your `content` declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/adultery-where.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/adultery-wish-to-name.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/desertion-agree.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/lived-apart-since.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/respondent-consent.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/help/with-fees.js
> +    if (appliedForFees) {
another candidate for following your content declaration on line 11

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 9

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/living-arrangements/live-together.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 16

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/husband-or-wife.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 9

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/married-in-uk.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 10

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
Is it worth testing upload in both of these tests? Otherwise you won't be testing that the 'Remove' button for an uploaded item is in the correct language

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 56

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/pay/pay-online-only.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 7

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/petitioner/confidential.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on lines 9 & 10

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/petitioner/contact-details.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 13

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/petitioner/use-home-address.js
> +    I.scrollPageToBottom();
another candidate for following your content declaration on line 11

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/prayer/claim-costs.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 8

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/respondent/use-home-address.js
> +    I.navByClick(commonContent.continue);
another candidate for following your content declaration on line 8

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/paths/save-resume.js
> +  // I.seeInCurrentUrl('/screening-questions/language-preference');
Are these not useful steps to prove that the draft has been deleted?

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
another candidate for following your content declaration on line 28

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
another candidate for following your content declaration on line 73

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
another candidate for following your content declaration on line 121

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/check-your-answers/check-your-answers.js
>  }
another candidate for following your dynamic language content declaration like in other files

2020-11-12 14:55 UTC, Rob-Doherty commented on test/end-to-end/pages/done-and-submitted/done-and-submitted.js
> +  }
another candidate for following your dynamic language content declaration like in other files

2020-11-13 09:45 UTC, Rob-Doherty requested changes
I still have a few suggestions / requests for changes:

- un-ignore a few scenarios (they're currently using `xScenario(...)` which is wrong)
- add your dynamic language declaration to a few more places to re-use steps
- a couple questions on some potentially useful test code being removed
- a bit of new code that doesn't look to be used

I really like the changes you've done @phaniperla to define the language content for the function and re-use the same steps - just needs to be used in a few more places.

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/desertion-date.js
> +  }
why would you only want to check this for English language? otherwise this function doesn't do anything for Welsh tests

2020-11-13 09:45 UTC, Rob-Doherty commented on bin/run-functional-tests.sh
> +export E2E_WAIT_FOR_TIMEOUT_VALUE=${E2E_WAIT_FOR_TIMEOUT_VALUE:-60000}
I'm still unsure about this

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/helpers/JSWait.js
> +  }
I still think this isn't being used, so should be removed

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/respondent-consent.js
> +    I.navByClick(commonContent.continue);
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
> +    I.navByClick(commonContent.continue);
still not needed

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/married-in-uk.js
> +  I.checkOption(contentEn.no);
Still unsure about this hardcoded English content

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
Still think it would be worth verifying the upload journey in both English and Welsh tests

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/upload.js
> -  I.dontSee('Remove');
I still think this would be good to have to verify that the item has actually been removed

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/marriage/upload.js
> +    I.navByClick(commonContent.continue);
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/pages/pay/pay-online-only.js
> +    I.navByClick(commonContent.continue);
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/jurisdictionConnections.js
> +xScenario('Re-set connections: Not confident at Connection Summary 1st time', function(I) {
Scenario still being ignored - needs to be enabled.

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/jurisdictionConnections.js
> +xScenario('Jurisdiction Exit: Petitioner does not have eligible jurisdiction.', function(I) {
Scenario still being ignored - needs to be enabled.

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +  xScenario(`${language.toUpperCase()} - 5 years separation E2E `, async function(I) {
Scenario still being ignored - needs to be enabled.

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Still think this could follow your content declaration pattern Phani

2020-11-13 09:45 UTC, Rob-Doherty commented on test/end-to-end/paths/save-resume.js
> +  // I.seeInCurrentUrl('/screening-questions/language-preference');
Still think these steps would be useful to keep in the test

2020-11-13 09:45 UTC, mhisltd approved these changes
LGTM - Approved

2020-11-13 11:07 UTC, phaniperla commented on test/end-to-end/pages/equality/equality.js
> +      I.seeCurrentUrlEquals(pagePath);
This has been addressed

2020-11-13 11:07 UTC, phaniperla commented on test/end-to-end/pages/financial/advice.js
> +  if (language === 'en') {
reviewer comments has been addressed

2020-11-13 11:08 UTC, phaniperla commented on test/end-to-end/pages/financial/arrangements.js
> +    I.navByClick(commonContent.continue);
reviewer comments has been addressed

2020-11-13 11:08 UTC, phaniperla commented on test/end-to-end/pages/address/postcode.js
> +    I.navByClick(commonContent.continue);
reviewer comments has been addressed

2020-11-13 11:08 UTC, phaniperla commented on test/end-to-end/pages/check-your-answers/check-your-answers.js
> +    I.checkMyAnswers('cy');
reviewer comments has been addressed

2020-11-13 11:09 UTC, phaniperla commented on test/end-to-end/pages/screening-questions/has-respondent-address.js
> +    I.retry(2).click(respondentAddContent.yes);
reviewer comments has been addressed

2020-11-13 11:09 UTC, phaniperla commented on test/end-to-end/pages/screening-questions/language-preference.js
> +    I.retry(2).click(languageContent.yes);
reviewer comments has been addressed

2020-11-13 11:09 UTC, phaniperla commented on test/end-to-end/paths/exitScenarios.js
> +}).retry(1);
it's one

2020-11-13 11:11 UTC, phaniperla commented on test/end-to-end/pages/address/postcode.js
> +  }
i got your point @Rob-Doherty , diffinetely  i will take care of that...

2020-11-13 11:12 UTC, phaniperla commented on test/end-to-end/helpers/JSWait.js
> +  }
Removed unused methods

2020-11-13 11:17 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/adultery-3rd-party-details.js
> +    I.navByClick(commonContent.continue);
Issue has been addressed

2020-11-13 11:18 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/adultery-second-hand-info.js
> +    I.fillField('reasonForDivorceAdulterySecondHandInfoDetails', mockSession.reasonForDivorceAdulterySecondHandInfoDetails);
Reviewer comments has been addressed

2020-11-13 11:18 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/adultery-when.js
> +    I.navByClick(commonContent.continue);
Reviewer comments has been addressed

2020-11-13 11:19 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
> +    I.navByClick(commonContent.continue);
Reviewer comments has been addressed

2020-11-13 11:19 UTC, phaniperla commented on test/end-to-end/pages/legal/legal-proceedings.js
> +    I.navByClick(commonContent.continue);
Reviewer comments has been addressed

2020-11-13 11:20 UTC, phaniperla commented on test/end-to-end/pages/living-arrangements/live-together.js
> +    I.navByClick(commonContent.continue);
Reviewer comments has been addressed

2020-11-13 11:23 UTC, phaniperla commented on bin/run-functional-tests.sh
> +export E2E_WAIT_FOR_TIMEOUT_VALUE=${E2E_WAIT_FOR_TIMEOUT_VALUE:-60000}
Sometime tests are failing due to time out issue, that could be the reason to increase the timeout value

2020-11-13 12:41 UTC, mounikahmcts approved these changes

2020-11-13 12:44 UTC, ruban72 approved these changes

2020-11-13 12:53 UTC, phaniperla commented on test/end-to-end/pages/done-and-submitted/done-and-submitted.js
> +  }
Reviewers comments has been addressed

2020-11-13 12:53 UTC, phaniperla commented on test/end-to-end/pages/check-your-answers/check-your-answers.js
>  }
Reviewers comments has been addressed

2020-11-13 12:53 UTC, phaniperla commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Reviewers comments has been addressed

2020-11-13 12:53 UTC, phaniperla commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Reviewers comments has been addressed

2020-11-13 12:54 UTC, phaniperla commented on test/end-to-end/pages/screening-questions/has-marriage-cert.js
> +    I.retry(2).click(marriageCertContent.yes);
Reviewers comments has been addressed

2020-11-13 12:54 UTC, phaniperla commented on test/end-to-end/pages/screening-questions/read-financial-remedy.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 12:55 UTC, phaniperla commented on test/end-to-end/paths/exitScenarios.js
> +}).retry(1);
Reviewers comments has been addressed

2020-11-13 12:55 UTC, phaniperla commented on bin/run-functional-tests.sh
> +export E2E_WAIT_FOR_TIMEOUT_VALUE=${E2E_WAIT_FOR_TIMEOUT_VALUE:-60000}
Reviewers comments has been addressed

2020-11-13 12:56 UTC, phaniperla commented on test/end-to-end/paths/reasonsForDivorce.js
> +    }
Reviewers comments has been addressed

2020-11-13 12:57 UTC, phaniperla commented on test/end-to-end/pages/address/postcode.js
> +  }
Reviewers comments has been addressed

2020-11-13 12:58 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/adultery-where.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 12:58 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/desertion-agree.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 12:58 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/desertion-details.js
> +  if (language === 'en') {
Reviewers comments has been addressed

2020-11-13 12:59 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/lived-apart-since.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 12:59 UTC, phaniperla commented on test/end-to-end/pages/grounds-for-divorce/reason.js
> +    I.waitForText(reason);
Reviewers comments has been addressed

2020-11-13 12:59 UTC, phaniperla commented on test/end-to-end/pages/help/need-help.js
> +    I.retry(2).click(needHelp ? needHelpContent.yes : needHelpContent.no);
Reviewers comments has been addressed

2020-11-13 13:00 UTC, phaniperla commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 13:00 UTC, phaniperla commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +    I.navByClick(commonContent.continue);
Reviewers comments has been addressed

2020-11-13 13:46 UTC, phaniperla commented on test/end-to-end/paths/reasonsForDivorce.js
> +  xScenario(`${language.toUpperCase()} - 5 years separation E2E `, async function(I) {
5+ years is going to Nightly pipeline

2020-11-13 13:48 UTC, phaniperla commented on test/end-to-end/pages/generic-error/generic-error.js
> +  }
Issue has been addressed

2020-11-13 13:48 UTC, phaniperla commented on test/end-to-end/pages/jurisdiction/habitual-residence.js
> +  }
issue has been addressed

2020-11-13 13:48 UTC, phaniperla commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +  I.checkOption(contentEn.needInfo);
no

2020-11-13 13:49 UTC, phaniperla commented on test/end-to-end/pages/living-arrangements/live-together.js
> +    I.checkOption(selectContentCy.yes);
issue has been addressed

2020-11-13 13:49 UTC, phaniperla commented on test/end-to-end/pages/marriage/married-in-uk.js
> +  I.checkOption(contentEn.no);
issue has been addressed

2020-11-13 13:50 UTC, phaniperla commented on test/end-to-end/pages/marriage/upload.js
> -  I.dontSee('Remove');
Click Remove() functionality is not working and issue has been addressed

2020-11-13 13:51 UTC, phaniperla commented on test/end-to-end/paths/jurisdictionConnections.js
> +xScenario('Re-set connections: Not confident at Connection Summary 1st time', function(I) {
Jurisdiction test is failing randomly in Preview but the same passed constantly in local. Therefore that test requires further investigation. There is separate JIRA dealing that issue

2020-11-13 13:52 UTC, phaniperla commented on test/end-to-end/paths/save-resume.js
> +  // I.seeInCurrentUrl('/screening-questions/language-preference');
issue has been addressed

2020-11-13 13:55 UTC, phaniperla commented
> A few points, mainly to do with
> 
> * consistently following your dynamic language declaration that avoids the need for multiple versions of the same steps
> * un-skipping scenarios
> * a couple questions on some potentially useful test code being removed
> * a bit of new code that doesn't look to be used

 Most of the review comments has been taken care

2020-11-13 14:02 UTC, mhisltd approved these changes
LGTM - Approved

2020-11-13 14:35 UTC, phaniperla commented
> I still have a few suggestions / requests for changes:
> 
> * un-ignore a few scenarios (they're currently using `xScenario(...)` which is wrong)
> * add your dynamic language declaration to a few more places to re-use steps
> * a couple questions on some potentially useful test code being removed
> * a bit of new code that doesn't look to be used
> 
> I really like the changes you've done @phaniperla to define the language content for the function and re-use the same steps - just needs to be used in a few more places.

2020-11-13 14:59 UTC, Rob-Doherty approved these changes
Spoken with @phaniperla and most of the items that didn't get covered in this PR will be done in the next. Approving to unblock the PR. 99% perfect! 👍

2020-11-13 14:59 UTC, Rob-Doherty commented on bin/run-functional-tests.sh
> +export E2E_WAIT_FOR_TIMEOUT_VALUE=${E2E_WAIT_FOR_TIMEOUT_VALUE:-60000}
I still feel like this could cause trouble for the pipelines by waiting too long, but for the sake of getting this PR in lets go with this and can alter it later if needed

2020-11-13 14:59 UTC, Rob-Doherty commented on test/end-to-end/pages/grounds-for-divorce/desertion-date.js
> +  }
I still think this check is needed for Welsh language tests - but we can discuss for a separate PR

2020-11-13 14:59 UTC, Rob-Doherty commented on test/end-to-end/pages/jurisdiction/interstitial.js
> +  I.checkOption(contentEn.needInfo);
so do you need to update it to work with both? Or is this function ONLY used in the English language tests?

2020-11-16 09:27 UTC, merged