DIV-6654: Map general referral states on Petitioner and Respondent apps
hmcts/div-petitioner-frontend pull request #799
Opened 2020-12-15 16:22 UTC by madjava

# Description

https://tools.hmcts.net/jira/browse/DIV-6654

Redirecting PFE to DN when case state `AwaitingGeneralReferralPayment` or `GeneralConsiderationComplete` state. DN already has facility to display a default informatory page for cases it does not specifically handle, no need to create on PFE

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-15 17:15 UTC, yarpo approved these changes

2020-12-16 11:16 UTC, jvictorcf approved these changes
Approved with a tiny comment.

2020-12-16 11:16 UTC, jvictorcf commented on app/middleware/redirectMiddleware.test.js
> +      const stateRedirectedToDn = ['AwaitingGeneralReferralPayment', 'GeneralConsiderationComplete'];
stateToRedirectToDn?

2020-12-16 11:19 UTC, jvictorcf requested changes
Actually. Are these states new (as in not in prod yet)?

2020-12-16 11:29 UTC, madjava commented on app/middleware/redirectMiddleware.test.js
> +      const stateRedirectedToDn = ['AwaitingGeneralReferralPayment', 'GeneralConsiderationComplete'];
Yup, any is fine by me

2020-12-16 11:37 UTC, madjava commented
> Actually. Are these states new (as in not in prod yet)?

New states. Features have not yet been released

2020-12-16 12:19 UTC, jvictorcf approved these changes

2020-12-16 14:40 UTC, yarpo approved these changes

2020-12-16 14:40 UTC, yarpo approved these changes

2021-01-04 16:04 UTC, merged