DIV-6760: Adjusting validation for solicitor email manual
hmcts/div-petitioner-frontend pull request #839
Opened 2021-03-19 11:35 UTC by Dizrupto

# Description

Adjusting validation for solicitor email manual

Fixes https://tools.hmcts.net/jira/browse/DIV-6760

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-19 11:59 UTC, yarpo approved these changes

2021-03-19 12:17 UTC, ravinderpal approved these changes

2021-03-19 12:27 UTC, johnoneill46 approved these changes

2021-03-19 13:11 UTC, yarpo requested changes
don;t merge it. Jeremy is using this deployment

2021-03-19 16:12 UTC, yarpo approved these changes

2021-03-22 09:53 UTC, yarpo approved these changes

2021-03-22 13:42 UTC, merged