DFR-37 deploy cookie banner
hmcts/div-petitioner-frontend pull request #895
Opened 2021-06-07 15:31 UTC by anatolysan

https://tools.hmcts.net/jira/browse/DFR-37

2021-06-08 13:40 UTC, ruban72 approved these changes

2022-01-18 09:25 UTC, ruban72 commented on app/steps/avaya-webchat/template.html
> +                {% if features.antennaWebchatNewApi %}
I think we need to back out this change as it should be features.antennaWebchatUserAttribute that is checked here

2022-01-18 09:28 UTC, ruban72 requested changes
Please see comments re apps/steps/avaya-webchat/template.html

2022-01-18 09:52 UTC, ruban72 approved these changes

2022-01-18 10:33 UTC, arun-hmcts approved these changes

2022-01-18 10:36 UTC, merged